routes/web.php
<?php

use App\Http\Controllers\CompenController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PresenceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SalaryController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';
Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');
Route::group(['middleware' => ['auth']], function () {
    //Route::resource('presensi', PresenceController::class);
    Route::resource('kompensasi', CompenController::class);
    Route::resource('karyawan', EmployeeController::class);
    //Route presensi
    Route::match(array('GET','POST'),'presensi', [PresenceController::class,'index'])->name('presensi.index');
    Route::post('presensi-store', [PresenceController::class,'store'])->name('presensi.store');
    //Route ubah profile
    Route::put('update-profile/{user}', [UserController::class,'update'])->name('update.profile');
    //Route laporan absensi
    Route::match(array('GET','POST'),'laporan', [ReportController::class,'index'])->name('laporan.index');
    Route::post('laporan-store', [ReportController::class,'store'])->name('laporan.store');
    //Route gaji
    Route::match(array('GET','POST'),'gaji', [SalaryController::class,'index'])->name('gaji.index');
    Route::post('gaji-store', [SalaryController::class,'store'])->name('gaji.store');
});

Route::get('/profile', function () {
    $user = auth()->user();
    return view('profile',compact('user'));
})->middleware(['auth'])->name('profile');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/gaji.blade.php
@extends('layouts.main',['title'=>'Pembayaran Gaji'])
@section('css')
    <link rel="stylesheet" href="{{ asset('packages/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Gaji</li>
    </ol>
@endsection
@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <form action="{{ route('gaji.index') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label class="label-control">Periode Tanggal</label>
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <input style="height: 32px" type="text" id="periode" name="periode" class="form-control datepicker" value="{{ $periode }}"/>
                        </div>
                        <div class="col-sm">
                            <input type="submit" name="Tampilkan" class="btn btn-sm btn-outline-primary" value="Tampilkan">
                        </div>
                    </div>
                </div>
            </form>
            <h4 class="card-title ">Daftar Gaji</h4>
            @if(auth()->user()->getOriginal('role')=='admin')
                @if (count($salaries)<=0)
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#hitung-gaji">Hitung Gaji</button>
                @endif
            @endif
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="table-presensi">
                <thead class=" text-primary">
                    <tr>
                        <th>Karyawan</th>
                        <th>Periode</th>
                        <th>Gaji Pokok</th>
                        <th>Tunjangan</th>
                        <th>Denda</th>
                        <th>Gaji Diterima</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($salaries as $gaji)
                        <tr>
                            <td>{{ ucfirst($gaji->report->user->name) }}</td>
                            <td>{{ Chantika::toLongDate($gaji->periode) }}</td>
                            <td class="text-right">{{ Chantika::toRupiah($gaji->gaji_pokok) }}</td>
                            <td class="text-right">{{ Chantika::toRupiah($gaji->tunjangan) }}</td>
                            <td class="text-right">{{ Chantika::toRupiah($gaji->denda) }}</td>
                            <td class="text-right">{{ Chantika::toRupiah($gaji->gaji_bersih) }}</td>
                        </tr>
                    @empty
                    @endforelse
                </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('modal')
    <x-modal id="hitung-gaji" title="Hitung Gaji">
        <form action="{{ route('gaji.store') }}" method="post">
            @csrf
            {{ csrf_field() }}
            <h4>Apakah anda yakin ingin menghitung gaji karyawan?</h4>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-success" value="Buat Laporan" />
            </div>
        </form>
    </x-modal>
@endsection
@section('js')
    <script src="{{ asset('packages/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('packages/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/moment.locale.id.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
    $('.datepicker').datetimepicker({
        locale: 'id',
        format: 'MM-YYYY',
        icons: {
            time: "fa fa-clock-o",
            date: "fa fa-calendar",
            up: "fa fa-chevron-up",
            down: "fa fa-chevron-down",
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'fa fa-screenshot',
            clear: 'fa fa-trash',
            close: 'fa fa-remove'
        }
    });
    $(document).ready(function() {
        $('#table-presensi').DataTable()
    })
    </script>
@endsection

resources/views/karyawan.blade.php
@extends('layouts.main',['title'=>'Karyawan'])
@section('css')
    <link rel="stylesheet" href="{{ asset('packages/datatables/dataTables.bootstrap4.min.css') }}">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Karyawan</li>
    </ol>
@endsection
@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title ">Daftar Karyawan</h4>
            <button class="btn btn-primary" data-toggle="modal" data-target="#tambah-karyawan">Tambah</button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="table-karyawan">
                <thead class=" text-primary">
                    <th>Nama</th>
                    <th>Jenis Kelamin</th>
                    <th>Email</th>
                    <th>Telepon</th>
                    <th>Alamat</th>
                </thead>
                <tbody>
                    @forelse ($users as $user)
                        <tr>
                            <td>{{ ucfirst($user->name) }}</td>
                            <td>{{ ucfirst($user->employee->jenis_kelamin) }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->employee->telepon }}</td>
                            <td>{{ $user->employee->alamat }}</td>
                        </tr>
                    @empty
                    @endforelse
                </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('modal')
    <x-modal id="tambah-karyawan" title="Tambah Karyawan">
        <form action="{{ route('karyawan.store') }}" method="post">
            {{ csrf_field() }}
            <x-input label="Nama" type="text" name="tambah_nama" required="true" placeholder="Masukkan nama karyawan"/>
            <x-select-sex id="tambah_jenis_kelamin" name="tambah_jenis_kelamin"  required="true"/>
            <x-input label="Alamat" type="text" name="tambah_alamat" required="true" placeholder="Masukkan alamat karyawan"/>
            <x-input label="Email" type="email" name="tambah_email" placeholder="Masukkan email karyawan jika ada"/>
            <x-input label="Telepon" type="text" name="tambah_telepon" required="true" placeholder="Masukkan nomor telepon karyawan"/>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-success" value="Simpan" />
            </div>
        </form>
    </x-modal>
    <x-modal id="hapus-karyawan" title="Hapus Karyawan">
        <form action="" method="delete">
            @csrf
            <h5>Anda yakin akan menghapus kompensasi ini?</h5>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-danger" value="Hapus" />
            </div>
        </form>
    </x-modal>
@endsection
@section('js')
    <script src="{{ asset('packages/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('packages/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('#table-karyawan').DataTable()
        })
    </script>
@endsection

resources/views/kompensasi.blade.php
@extends('layouts.main',['title'=>'Kompensasi'])
@section('css')
    <link rel="stylesheet" href="{{ asset('packages/datatables/dataTables.bootstrap4.min.css') }}">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Kompensasi</li>
    </ol>
@endsection
@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <h4 class="card-title ">Daftar Kompensasi</h4>
            <button class="btn btn-primary" data-toggle="modal" data-target="#tambah-kompensasi">Tambah</button>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="table-kompensasi">
                <thead class=" text-primary">
                    <th>Nama</th>
                    <th>Nominal</th>
                    <th>Jenis</th>
                    <th>Aksi</th>
                </thead>
                <tbody>
                    @forelse ($compens as $compen)
                        <tr>
                            <td>{{ $compen->nama }}</td>
                            <td class="text-right">{{ Chantika::toRupiah($compen->nominal) }}</td>
                            <td>{{ $compen->jenis }}</td>
                            <td>
                                <button class="btn btn-primary" data-toggle="modal" data-target="#ubah-kompensasi" onclick="ubah({{ $compen->id }})">Ubah</button>
                                <button class="btn btn-danger" data-toggle="modal" data-target="#hapus-kompensasi" onclick="hapus({{ $compen->id }})">Hapus</button>
                            </td>
                        </tr>
                    @empty
                    @endforelse
                </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('modal')
    <x-modal id="tambah-kompensasi" title="Tambah Kompensasi">
        <form action="{{ route('kompensasi.store') }}" method="post">
            @csrf
            <x-input label="Nama" type="text" name="tambah_nama" placeholder="Masukkan nama kompensasi" required="true"/>
            <x-input label="Nominal" type="text" name="tambah_nominal" placeholder="Masukkan nominal kompensasi" required="true"/>
            <x-select-kompensasi id="tambah_jenis" name="tambah_jenis" />
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-success" value="Simpan" />
            </div>
        </form>
    </x-modal>
    <x-modal id="ubah-kompensasi" title="Ubah Kompensasi">
        <form action="{{ route('kompensasi.update',1) }}" id="form_ubah" method="post">
            @csrf
            @method('PUT')
            <x-input label="Nama" type="text" name="ubah_nama" id="ubah_nama" required="true"/>
            <x-input label="Nominal" type="text" name="ubah_nominal" id="ubah_nominal" required="true"/>
            <x-select-kompensasi id="ubah_jenis" name="ubah_jenis" />
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-success" value="Ubah"/>
            </div>
        </form>
    </x-modal>
    <x-modal id="hapus-kompensasi" title="Hapus Kompensasi">
        <form action="" method="post" id="form_hapus">
            @csrf
            @method('delete')
            <h5>Anda yakin akan menghapus kompensasi ini?</h5>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-danger" value="Hapus" />
            </div>
        </form>
    </x-modal>
@endsection
@section('js')
    <script src="{{ asset('packages/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('packages/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script>
    $(document).ready(function() {
        $('#table-kompensasi').DataTable()
    })

    function ubah(id){
        var urlUpdate = "{{ route('kompensasi.update', "-id-") }}".replace('-id-', id)
        $('#form_ubah').prop('action',urlUpdate)
        let urlShow="{{ route('kompensasi.show', ['kompensasi'=>'-id-']) }}".replace('-id-', id)
        $.ajax({
            type: "GET",
            url: urlShow,
            cache: false,
            success: function(result){
                $("#ubah_nama").val(result.nama)
                $("#ubah_nominal").val(result.nominal)
                $("#ubah_jenis").val(result.jenis)
            },
            error: function (request, status, error) {
                console.log(error)
            }
        })
    }
    function hapus(id){
        var urlUpdate = "{{ route('kompensasi.destroy', "-id-") }}".replace('-id-', id)
        $('#form_hapus').prop('action',urlUpdate)
    }
    </script>
@endsection

resources/views/laporan.blade.php
@extends('layouts.main',['title'=>'Laporan'])
@section('css')
    <link rel="stylesheet" href="{{ asset('packages/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Laporan</li>
    </ol>
@endsection
@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <form action="{{ route('laporan.index') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label class="label-control">Periode Tanggal</label>
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <input style="height: 32px" type="text" id="periode" name="periode" class="form-control datepicker" value="{{ $periode }}"/>
                        </div>
                        <div class="col-sm">
                            <input type="submit" name="Tampilkan" class="btn btn-sm btn-outline-primary" value="Tampilkan">
                        </div>
                    </div>
                </div>
            </form>
            {{-- <x-select-month-year idMonth="pilih_bulan" nameMonth="pilih_bulan" valueMonth="{{ $bulan }}" idYear="pilih_tahun" nameYear="pilih_tahun" valueYear="{{ $tahun }}"/> --}}
            <h4 class="card-title ">Daftar Laporan</h4>
            @if(auth()->user()->getOriginal('role')=='admin')
                @if (count($reports)<=0)
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#buat-laporan">Buat Laporan</button>
                @endif
            @endif
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="table-laporan">
                <thead class=" text-primary">
                    <th>Periode</th>
                    <th>Karyawan</th>
                    <th>Presensi</th>
                    <th>Absensi</th>
                    <th>Terlambat</th>
                    <th>Lembur</th>
                </thead>
                <tbody>
                    @forelse ($reports as $laporan)
                        <tr>
                            <td>{{ Chantika::toLongDate($laporan->periode) }}</td>
                            <td>{{ ucfirst($laporan->user->name)  }}</td>
                            <td>{{ $laporan->total_presensi }} kali</td>
                            <td>{{ $laporan->total_absensi }} kali</td>
                            <td>{{ $laporan->total_terlambat }} menit</td>
                            <td>{{ $laporan->total_lembur }} menit</td>
                        </tr>
                    @empty
                    @endforelse
                </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('modal')
    <x-modal id="buat-laporan" title="Buat Laporan Presensi">
        <form action="{{ route('laporan.store') }}" method="post">
            @csrf
            {{ csrf_field() }}
            <h4>Apakah anda yakin ingin membuat laporan presensi?</h4>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-success" value="Buat Laporan" />
            </div>
        </form>
    </x-modal>
@endsection
@section('js')
    <script src="{{ asset('packages/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('packages/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/moment.locale.id.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>

    <script>
    $('.datepicker').datetimepicker({
        locale: 'id',
        format: 'MM-YYYY',
        icons: {
            time: "fa fa-clock-o",
            date: "fa fa-calendar",
            up: "fa fa-chevron-up",
            down: "fa fa-chevron-down",
            previous: 'fa fa-chevron-left',
            next: 'fa fa-chevron-right',
            today: 'fa fa-screenshot',
            clear: 'fa fa-trash',
            close: 'fa fa-remove'
        }
    });
    $(document).ready(function() {
        $('#table-laporan').DataTable()
    })
    </script>
@endsection

resources/views/presensi.blade.php
@extends('layouts.main',['title'=>'Presensi'])
@section('css')
    <link rel="stylesheet" href="{{ asset('packages/datatables/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Presensi</li>
    </ol>
@endsection
@section('content')
    <div class="card">
        <div class="card-header card-header-primary">
            <form action="{{ route('presensi.index') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label class="label-control">Periode Tanggal</label>
                    <div class="row no-gutters">
                        <div class="col-sm-2">
                            <input style="height: 32px" type="text" id="periode" name="periode" class="form-control datepicker" value="{{ $periode }}"/>
                        </div>
                        <div class="col-sm">
                            <input type="submit" name="Tampilkan" class="btn btn-sm btn-outline-primary" value="Tampilkan">
                        </div>
                    </div>
                </div>
            </form>
            <h4 class="card-title ">Riwayat Presensi</h4>
            @if(auth()->user()->getOriginal('role')=='karyawan')
                <form action="{{ route('presensi.store') }}" method="POST">
                    @csrf
                    @if (!auth()->user()->isClockIn())
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#presensi-clockin">Clock-in</button>
                        {{-- <input type="submit" class="btn btn-primary" name="submit" value="Clock-in"> --}}
                    @elseif(!auth()->user()->isClockOut())
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#presensi-clockout">Clock-out</button>
                        {{-- <input type="submit" class="btn btn-warning" name="submit" value="Clock-out"> --}}
                    @else
                        <h4>Anda sudah presensi pulang</h4>
                    @endif
                </form>
            @endif
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table" id="table-presensi">
                <thead class=" text-primary">
                    @if(auth()->user()->getOriginal('role')=='admin')
                        <th>Karyawan</th>
                    @endif
                    <th>Periode</th>
                    <th>Masuk</th>
                    <th>Keluar</th>
                </thead>
                <tbody>
                    @foreach ($presences as $presensi)
                        <tr>
                            @if(auth()->user()->getOriginal('role')=='admin')
                                <td>{{ $presensi->user->name }}</td>
                            @endif
                            <td>{{ Chantika::toLongDate($presensi->periode) }}</td>
                            <td>{{ Chantika::toTime($presensi->clockin) }}</td>
                            <td>{{ ($presensi->clockout) ? Chantika::toTime($presensi->clockout): '-'  }}</td>
                        </tr>
                    @endforeach
                </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@section('modal')
    <x-modal id="presensi-clockin" title="Presensi Masuk">
        <form action="{{ route('presensi.store') }}" method="post">
            {{ csrf_field() }}
            <h4>Apakah anda yakin ingin presensi masuk?</h4>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-success" value="Clock-in" />
            </div>
        </form>
    </x-modal>
    <x-modal id="presensi-clockout" title="Presensi Keluar">
        <form action="{{ route('presensi.store') }}" method="post">
            {{ csrf_field() }}
            <h4>Apakah anda yakin ingin presensi keluar?</h4>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                <input type="submit" class="btn btn-warning" value="Clock-out" />
            </div>
        </form>
    </x-modal>
@endsection
@section('js')
    <script src="{{ asset('packages/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('packages/datatables/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/moment.locale.id.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
    <script>
        $('.datepicker').datetimepicker({
            locale: 'id',
            format: 'MM-YYYY',
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            }
        });
    $(document).ready(function() {
        $('#table-presensi').DataTable()
    })
    </script>
@endsection

resources/views/profile.blade.php
@extends('layouts.main',['title'=>'Profile'])
@section('css')
    <link rel="stylesheet" href="{{ asset('packages/datatables/dataTables.bootstrap4.min.css') }}">
@endsection
@section('breadcrumb')
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="./">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Profile</li>
    </ol>
@endsection
@section('content')
    <div class="card">
        <div class="card-body">
            <form action="{{ route('update.profile',$user->id) }}" method="post">
                @method('put')
                @csrf
                <div class="row">
                    <div class="col">
                        <div class="form-group">
                            <label for="nama">Nama</label>
                            <input type="text" class="form-control" id="ubah_nama" name="ubah_nama" value="{{ $user->name }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" class="form-control" id="ubah_email" name="ubah_email" value="{{ $user->email }}">
                        </div>
                        <div class="form-group">
                            <label for="telepon">Telepon</label>
                            <input type="text" class="form-control" id="ubah_telepon" name="ubah_telepon" value="{{ $user->employee->telepon }}">
                        </div>
                        <input type="submit" class="btn btn-primary" value="Ubah">
                    </div>
                    <div class="col">
                        <div class="form-group">
                            <label for="jenisKelamin">Jenis Kelamin</label>
                            <input type="text" class="form-control" id="ubah_jenis_kelamin" name="ubah_jenis_kelamin" value="{{ $user->employee->jenis_kelamin }}">
                        </div>
                        <div class="form-group">
                            <label for="alamat">Alamat</label>
                            <textarea name="ubah_alamat" class="form-control" id="ubah_alamat" name="ubah_alamat" rows="4">{{ $user->employee->alamat }}</textarea>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('js')
    <script src="{{ asset('packages/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('packages/datatables/dataTables.bootstrap4.min.js') }}"></script>
@endsection